/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupermarketsRouteImport } from './routes/supermarkets'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupermarketsIndexRouteImport } from './routes/supermarkets.index'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as SupermarketsAddRouteImport } from './routes/supermarkets.add'
import { Route as ItemsAddRouteImport } from './routes/items.add'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as ItemsIdIndexRouteImport } from './routes/items.$id.index'
import { Route as SupermarketsIdEditRouteImport } from './routes/supermarkets.$id.edit'
import { Route as ItemsIdEditRouteImport } from './routes/items.$id.edit'
import { Route as ItemsIdAddRouteImport } from './routes/items.$id.add'
import { Route as ItemsIdPricesPriceIdEditRouteImport } from './routes/items.$id.prices.$priceId.edit'

const SupermarketsRoute = SupermarketsRouteImport.update({
  id: '/supermarkets',
  path: '/supermarkets',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupermarketsIndexRoute = SupermarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupermarketsRoute,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsRoute,
} as any)
const SupermarketsAddRoute = SupermarketsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => SupermarketsRoute,
} as any)
const ItemsAddRoute = ItemsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsIdIndexRoute = ItemsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsIdRoute,
} as any)
const SupermarketsIdEditRoute = SupermarketsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => SupermarketsRoute,
} as any)
const ItemsIdEditRoute = ItemsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdAddRoute = ItemsIdAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdPricesPriceIdEditRoute =
  ItemsIdPricesPriceIdEditRouteImport.update({
    id: '/prices/$priceId/edit',
    path: '/prices/$priceId/edit',
    getParentRoute: () => ItemsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteWithChildren
  '/supermarkets': typeof SupermarketsRouteWithChildren
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/add': typeof ItemsAddRoute
  '/supermarkets/add': typeof SupermarketsAddRoute
  '/items/': typeof ItemsIndexRoute
  '/supermarkets/': typeof SupermarketsIndexRoute
  '/items/$id/add': typeof ItemsIdAddRoute
  '/items/$id/edit': typeof ItemsIdEditRoute
  '/supermarkets/$id/edit': typeof SupermarketsIdEditRoute
  '/items/$id/': typeof ItemsIdIndexRoute
  '/items/$id/prices/$priceId/edit': typeof ItemsIdPricesPriceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items/add': typeof ItemsAddRoute
  '/supermarkets/add': typeof SupermarketsAddRoute
  '/items': typeof ItemsIndexRoute
  '/supermarkets': typeof SupermarketsIndexRoute
  '/items/$id/add': typeof ItemsIdAddRoute
  '/items/$id/edit': typeof ItemsIdEditRoute
  '/supermarkets/$id/edit': typeof SupermarketsIdEditRoute
  '/items/$id': typeof ItemsIdIndexRoute
  '/items/$id/prices/$priceId/edit': typeof ItemsIdPricesPriceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteWithChildren
  '/supermarkets': typeof SupermarketsRouteWithChildren
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/add': typeof ItemsAddRoute
  '/supermarkets/add': typeof SupermarketsAddRoute
  '/items/': typeof ItemsIndexRoute
  '/supermarkets/': typeof SupermarketsIndexRoute
  '/items/$id/add': typeof ItemsIdAddRoute
  '/items/$id/edit': typeof ItemsIdEditRoute
  '/supermarkets/$id/edit': typeof SupermarketsIdEditRoute
  '/items/$id/': typeof ItemsIdIndexRoute
  '/items/$id/prices/$priceId/edit': typeof ItemsIdPricesPriceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/items'
    | '/supermarkets'
    | '/items/$id'
    | '/items/add'
    | '/supermarkets/add'
    | '/items/'
    | '/supermarkets/'
    | '/items/$id/add'
    | '/items/$id/edit'
    | '/supermarkets/$id/edit'
    | '/items/$id/'
    | '/items/$id/prices/$priceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/items/add'
    | '/supermarkets/add'
    | '/items'
    | '/supermarkets'
    | '/items/$id/add'
    | '/items/$id/edit'
    | '/supermarkets/$id/edit'
    | '/items/$id'
    | '/items/$id/prices/$priceId/edit'
  id:
    | '__root__'
    | '/'
    | '/items'
    | '/supermarkets'
    | '/items/$id'
    | '/items/add'
    | '/supermarkets/add'
    | '/items/'
    | '/supermarkets/'
    | '/items/$id/add'
    | '/items/$id/edit'
    | '/supermarkets/$id/edit'
    | '/items/$id/'
    | '/items/$id/prices/$priceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  SupermarketsRoute: typeof SupermarketsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supermarkets': {
      id: '/supermarkets'
      path: '/supermarkets'
      fullPath: '/supermarkets'
      preLoaderRoute: typeof SupermarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supermarkets/': {
      id: '/supermarkets/'
      path: '/'
      fullPath: '/supermarkets/'
      preLoaderRoute: typeof SupermarketsIndexRouteImport
      parentRoute: typeof SupermarketsRoute
    }
    '/items/': {
      id: '/items/'
      path: '/'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/supermarkets/add': {
      id: '/supermarkets/add'
      path: '/add'
      fullPath: '/supermarkets/add'
      preLoaderRoute: typeof SupermarketsAddRouteImport
      parentRoute: typeof SupermarketsRoute
    }
    '/items/add': {
      id: '/items/add'
      path: '/add'
      fullPath: '/items/add'
      preLoaderRoute: typeof ItemsAddRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/$id/': {
      id: '/items/$id/'
      path: '/'
      fullPath: '/items/$id/'
      preLoaderRoute: typeof ItemsIdIndexRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/supermarkets/$id/edit': {
      id: '/supermarkets/$id/edit'
      path: '/$id/edit'
      fullPath: '/supermarkets/$id/edit'
      preLoaderRoute: typeof SupermarketsIdEditRouteImport
      parentRoute: typeof SupermarketsRoute
    }
    '/items/$id/edit': {
      id: '/items/$id/edit'
      path: '/edit'
      fullPath: '/items/$id/edit'
      preLoaderRoute: typeof ItemsIdEditRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/add': {
      id: '/items/$id/add'
      path: '/add'
      fullPath: '/items/$id/add'
      preLoaderRoute: typeof ItemsIdAddRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/prices/$priceId/edit': {
      id: '/items/$id/prices/$priceId/edit'
      path: '/prices/$priceId/edit'
      fullPath: '/items/$id/prices/$priceId/edit'
      preLoaderRoute: typeof ItemsIdPricesPriceIdEditRouteImport
      parentRoute: typeof ItemsIdRoute
    }
  }
}

interface ItemsIdRouteChildren {
  ItemsIdAddRoute: typeof ItemsIdAddRoute
  ItemsIdEditRoute: typeof ItemsIdEditRoute
  ItemsIdIndexRoute: typeof ItemsIdIndexRoute
  ItemsIdPricesPriceIdEditRoute: typeof ItemsIdPricesPriceIdEditRoute
}

const ItemsIdRouteChildren: ItemsIdRouteChildren = {
  ItemsIdAddRoute: ItemsIdAddRoute,
  ItemsIdEditRoute: ItemsIdEditRoute,
  ItemsIdIndexRoute: ItemsIdIndexRoute,
  ItemsIdPricesPriceIdEditRoute: ItemsIdPricesPriceIdEditRoute,
}

const ItemsIdRouteWithChildren =
  ItemsIdRoute._addFileChildren(ItemsIdRouteChildren)

interface ItemsRouteChildren {
  ItemsIdRoute: typeof ItemsIdRouteWithChildren
  ItemsAddRoute: typeof ItemsAddRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsIdRoute: ItemsIdRouteWithChildren,
  ItemsAddRoute: ItemsAddRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

interface SupermarketsRouteChildren {
  SupermarketsAddRoute: typeof SupermarketsAddRoute
  SupermarketsIndexRoute: typeof SupermarketsIndexRoute
  SupermarketsIdEditRoute: typeof SupermarketsIdEditRoute
}

const SupermarketsRouteChildren: SupermarketsRouteChildren = {
  SupermarketsAddRoute: SupermarketsAddRoute,
  SupermarketsIndexRoute: SupermarketsIndexRoute,
  SupermarketsIdEditRoute: SupermarketsIdEditRoute,
}

const SupermarketsRouteWithChildren = SupermarketsRoute._addFileChildren(
  SupermarketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRouteWithChildren,
  SupermarketsRoute: SupermarketsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
